// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/rickcts/srp/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rickcts/srp/ent/user"
	"github.com/rickcts/srp/ent/userauth"
	"github.com/rickcts/srp/ent/userauthevent"
	"github.com/rickcts/srp/ent/usermfa"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserAuth is the client for interacting with the UserAuth builders.
	UserAuth *UserAuthClient
	// UserAuthEvent is the client for interacting with the UserAuthEvent builders.
	UserAuthEvent *UserAuthEventClient
	// UserMFA is the client for interacting with the UserMFA builders.
	UserMFA *UserMFAClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.User = NewUserClient(c.config)
	c.UserAuth = NewUserAuthClient(c.config)
	c.UserAuthEvent = NewUserAuthEventClient(c.config)
	c.UserMFA = NewUserMFAClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		User:          NewUserClient(cfg),
		UserAuth:      NewUserAuthClient(cfg),
		UserAuthEvent: NewUserAuthEventClient(cfg),
		UserMFA:       NewUserMFAClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		User:          NewUserClient(cfg),
		UserAuth:      NewUserAuthClient(cfg),
		UserAuthEvent: NewUserAuthEventClient(cfg),
		UserMFA:       NewUserMFAClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		User.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.User.Use(hooks...)
	c.UserAuth.Use(hooks...)
	c.UserAuthEvent.Use(hooks...)
	c.UserMFA.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.User.Intercept(interceptors...)
	c.UserAuth.Intercept(interceptors...)
	c.UserAuthEvent.Intercept(interceptors...)
	c.UserMFA.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *UserAuthMutation:
		return c.UserAuth.mutate(ctx, m)
	case *UserAuthEventMutation:
		return c.UserAuthEvent.mutate(ctx, m)
	case *UserMFAMutation:
		return c.UserMFA.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUserAuth queries the userAuth edge of a User.
func (c *UserClient) QueryUserAuth(u *User) *UserAuthQuery {
	query := (&UserAuthClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(userauth.Table, userauth.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.UserAuthTable, user.UserAuthColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUserMFA queries the userMFA edge of a User.
func (c *UserClient) QueryUserMFA(u *User) *UserMFAQuery {
	query := (&UserMFAClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(usermfa.Table, usermfa.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.UserMFATable, user.UserMFAColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUserAuthEvent queries the userAuthEvent edge of a User.
func (c *UserClient) QueryUserAuthEvent(u *User) *UserAuthEventQuery {
	query := (&UserAuthEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(userauthevent.Table, userauthevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.UserAuthEventTable, user.UserAuthEventColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// UserAuthClient is a client for the UserAuth schema.
type UserAuthClient struct {
	config
}

// NewUserAuthClient returns a client for the UserAuth from the given config.
func NewUserAuthClient(c config) *UserAuthClient {
	return &UserAuthClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userauth.Hooks(f(g(h())))`.
func (c *UserAuthClient) Use(hooks ...Hook) {
	c.hooks.UserAuth = append(c.hooks.UserAuth, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userauth.Intercept(f(g(h())))`.
func (c *UserAuthClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserAuth = append(c.inters.UserAuth, interceptors...)
}

// Create returns a builder for creating a UserAuth entity.
func (c *UserAuthClient) Create() *UserAuthCreate {
	mutation := newUserAuthMutation(c.config, OpCreate)
	return &UserAuthCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserAuth entities.
func (c *UserAuthClient) CreateBulk(builders ...*UserAuthCreate) *UserAuthCreateBulk {
	return &UserAuthCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserAuthClient) MapCreateBulk(slice any, setFunc func(*UserAuthCreate, int)) *UserAuthCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserAuthCreateBulk{err: fmt.Errorf("calling to UserAuthClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserAuthCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserAuthCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserAuth.
func (c *UserAuthClient) Update() *UserAuthUpdate {
	mutation := newUserAuthMutation(c.config, OpUpdate)
	return &UserAuthUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserAuthClient) UpdateOne(ua *UserAuth) *UserAuthUpdateOne {
	mutation := newUserAuthMutation(c.config, OpUpdateOne, withUserAuth(ua))
	return &UserAuthUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserAuthClient) UpdateOneID(id int) *UserAuthUpdateOne {
	mutation := newUserAuthMutation(c.config, OpUpdateOne, withUserAuthID(id))
	return &UserAuthUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserAuth.
func (c *UserAuthClient) Delete() *UserAuthDelete {
	mutation := newUserAuthMutation(c.config, OpDelete)
	return &UserAuthDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserAuthClient) DeleteOne(ua *UserAuth) *UserAuthDeleteOne {
	return c.DeleteOneID(ua.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserAuthClient) DeleteOneID(id int) *UserAuthDeleteOne {
	builder := c.Delete().Where(userauth.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserAuthDeleteOne{builder}
}

// Query returns a query builder for UserAuth.
func (c *UserAuthClient) Query() *UserAuthQuery {
	return &UserAuthQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserAuth},
		inters: c.Interceptors(),
	}
}

// Get returns a UserAuth entity by its id.
func (c *UserAuthClient) Get(ctx context.Context, id int) (*UserAuth, error) {
	return c.Query().Where(userauth.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserAuthClient) GetX(ctx context.Context, id int) *UserAuth {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UserAuth.
func (c *UserAuthClient) QueryUser(ua *UserAuth) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ua.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(userauth.Table, userauth.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userauth.UserTable, userauth.UserColumn),
		)
		fromV = sqlgraph.Neighbors(ua.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserAuthClient) Hooks() []Hook {
	return c.hooks.UserAuth
}

// Interceptors returns the client interceptors.
func (c *UserAuthClient) Interceptors() []Interceptor {
	return c.inters.UserAuth
}

func (c *UserAuthClient) mutate(ctx context.Context, m *UserAuthMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserAuthCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserAuthUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserAuthUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserAuthDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserAuth mutation op: %q", m.Op())
	}
}

// UserAuthEventClient is a client for the UserAuthEvent schema.
type UserAuthEventClient struct {
	config
}

// NewUserAuthEventClient returns a client for the UserAuthEvent from the given config.
func NewUserAuthEventClient(c config) *UserAuthEventClient {
	return &UserAuthEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userauthevent.Hooks(f(g(h())))`.
func (c *UserAuthEventClient) Use(hooks ...Hook) {
	c.hooks.UserAuthEvent = append(c.hooks.UserAuthEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userauthevent.Intercept(f(g(h())))`.
func (c *UserAuthEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserAuthEvent = append(c.inters.UserAuthEvent, interceptors...)
}

// Create returns a builder for creating a UserAuthEvent entity.
func (c *UserAuthEventClient) Create() *UserAuthEventCreate {
	mutation := newUserAuthEventMutation(c.config, OpCreate)
	return &UserAuthEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserAuthEvent entities.
func (c *UserAuthEventClient) CreateBulk(builders ...*UserAuthEventCreate) *UserAuthEventCreateBulk {
	return &UserAuthEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserAuthEventClient) MapCreateBulk(slice any, setFunc func(*UserAuthEventCreate, int)) *UserAuthEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserAuthEventCreateBulk{err: fmt.Errorf("calling to UserAuthEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserAuthEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserAuthEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserAuthEvent.
func (c *UserAuthEventClient) Update() *UserAuthEventUpdate {
	mutation := newUserAuthEventMutation(c.config, OpUpdate)
	return &UserAuthEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserAuthEventClient) UpdateOne(uae *UserAuthEvent) *UserAuthEventUpdateOne {
	mutation := newUserAuthEventMutation(c.config, OpUpdateOne, withUserAuthEvent(uae))
	return &UserAuthEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserAuthEventClient) UpdateOneID(id int) *UserAuthEventUpdateOne {
	mutation := newUserAuthEventMutation(c.config, OpUpdateOne, withUserAuthEventID(id))
	return &UserAuthEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserAuthEvent.
func (c *UserAuthEventClient) Delete() *UserAuthEventDelete {
	mutation := newUserAuthEventMutation(c.config, OpDelete)
	return &UserAuthEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserAuthEventClient) DeleteOne(uae *UserAuthEvent) *UserAuthEventDeleteOne {
	return c.DeleteOneID(uae.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserAuthEventClient) DeleteOneID(id int) *UserAuthEventDeleteOne {
	builder := c.Delete().Where(userauthevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserAuthEventDeleteOne{builder}
}

// Query returns a query builder for UserAuthEvent.
func (c *UserAuthEventClient) Query() *UserAuthEventQuery {
	return &UserAuthEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserAuthEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a UserAuthEvent entity by its id.
func (c *UserAuthEventClient) Get(ctx context.Context, id int) (*UserAuthEvent, error) {
	return c.Query().Where(userauthevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserAuthEventClient) GetX(ctx context.Context, id int) *UserAuthEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UserAuthEvent.
func (c *UserAuthEventClient) QueryUser(uae *UserAuthEvent) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := uae.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(userauthevent.Table, userauthevent.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userauthevent.UserTable, userauthevent.UserColumn),
		)
		fromV = sqlgraph.Neighbors(uae.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserAuthEventClient) Hooks() []Hook {
	return c.hooks.UserAuthEvent
}

// Interceptors returns the client interceptors.
func (c *UserAuthEventClient) Interceptors() []Interceptor {
	return c.inters.UserAuthEvent
}

func (c *UserAuthEventClient) mutate(ctx context.Context, m *UserAuthEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserAuthEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserAuthEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserAuthEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserAuthEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserAuthEvent mutation op: %q", m.Op())
	}
}

// UserMFAClient is a client for the UserMFA schema.
type UserMFAClient struct {
	config
}

// NewUserMFAClient returns a client for the UserMFA from the given config.
func NewUserMFAClient(c config) *UserMFAClient {
	return &UserMFAClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usermfa.Hooks(f(g(h())))`.
func (c *UserMFAClient) Use(hooks ...Hook) {
	c.hooks.UserMFA = append(c.hooks.UserMFA, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usermfa.Intercept(f(g(h())))`.
func (c *UserMFAClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserMFA = append(c.inters.UserMFA, interceptors...)
}

// Create returns a builder for creating a UserMFA entity.
func (c *UserMFAClient) Create() *UserMFACreate {
	mutation := newUserMFAMutation(c.config, OpCreate)
	return &UserMFACreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserMFA entities.
func (c *UserMFAClient) CreateBulk(builders ...*UserMFACreate) *UserMFACreateBulk {
	return &UserMFACreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserMFAClient) MapCreateBulk(slice any, setFunc func(*UserMFACreate, int)) *UserMFACreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserMFACreateBulk{err: fmt.Errorf("calling to UserMFAClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserMFACreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserMFACreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserMFA.
func (c *UserMFAClient) Update() *UserMFAUpdate {
	mutation := newUserMFAMutation(c.config, OpUpdate)
	return &UserMFAUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserMFAClient) UpdateOne(um *UserMFA) *UserMFAUpdateOne {
	mutation := newUserMFAMutation(c.config, OpUpdateOne, withUserMFA(um))
	return &UserMFAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserMFAClient) UpdateOneID(id int) *UserMFAUpdateOne {
	mutation := newUserMFAMutation(c.config, OpUpdateOne, withUserMFAID(id))
	return &UserMFAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserMFA.
func (c *UserMFAClient) Delete() *UserMFADelete {
	mutation := newUserMFAMutation(c.config, OpDelete)
	return &UserMFADelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserMFAClient) DeleteOne(um *UserMFA) *UserMFADeleteOne {
	return c.DeleteOneID(um.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserMFAClient) DeleteOneID(id int) *UserMFADeleteOne {
	builder := c.Delete().Where(usermfa.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserMFADeleteOne{builder}
}

// Query returns a query builder for UserMFA.
func (c *UserMFAClient) Query() *UserMFAQuery {
	return &UserMFAQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserMFA},
		inters: c.Interceptors(),
	}
}

// Get returns a UserMFA entity by its id.
func (c *UserMFAClient) Get(ctx context.Context, id int) (*UserMFA, error) {
	return c.Query().Where(usermfa.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserMFAClient) GetX(ctx context.Context, id int) *UserMFA {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UserMFA.
func (c *UserMFAClient) QueryUser(um *UserMFA) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := um.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usermfa.Table, usermfa.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usermfa.UserTable, usermfa.UserColumn),
		)
		fromV = sqlgraph.Neighbors(um.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserMFAClient) Hooks() []Hook {
	return c.hooks.UserMFA
}

// Interceptors returns the client interceptors.
func (c *UserMFAClient) Interceptors() []Interceptor {
	return c.inters.UserMFA
}

func (c *UserMFAClient) mutate(ctx context.Context, m *UserMFAMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserMFACreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserMFAUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserMFAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserMFADelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserMFA mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		User, UserAuth, UserAuthEvent, UserMFA []ent.Hook
	}
	inters struct {
		User, UserAuth, UserAuthEvent, UserMFA []ent.Interceptor
	}
)
