// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rickcts/srp/ent/user"
	"github.com/rickcts/srp/ent/userauth"
)

// UserAuth is the model entity for the UserAuth schema.
type UserAuth struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// AuthExtras holds the value of the "auth_extras" field.
	AuthExtras string `json:"auth_extras,omitempty"`
	// AuthProvider holds the value of the "auth_provider" field.
	AuthProvider string `json:"auth_provider,omitempty"`
	// AuthID holds the value of the "auth_id" field.
	AuthID string `json:"auth_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserAuthQuery when eager-loading is set.
	Edges        UserAuthEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserAuthEdges holds the relations/edges for other nodes in the graph.
type UserAuthEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserAuthEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAuth) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userauth.FieldID, userauth.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userauth.FieldAuthExtras, userauth.FieldAuthProvider, userauth.FieldAuthID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAuth fields.
func (ua *UserAuth) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userauth.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ua.ID = int(value.Int64)
		case userauth.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ua.UserID = int(value.Int64)
			}
		case userauth.FieldAuthExtras:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_extras", values[i])
			} else if value.Valid {
				ua.AuthExtras = value.String
			}
		case userauth.FieldAuthProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_provider", values[i])
			} else if value.Valid {
				ua.AuthProvider = value.String
			}
		case userauth.FieldAuthID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_id", values[i])
			} else if value.Valid {
				ua.AuthID = value.String
			}
		default:
			ua.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAuth.
// This includes values selected through modifiers, order, etc.
func (ua *UserAuth) Value(name string) (ent.Value, error) {
	return ua.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserAuth entity.
func (ua *UserAuth) QueryUser() *UserQuery {
	return NewUserAuthClient(ua.config).QueryUser(ua)
}

// Update returns a builder for updating this UserAuth.
// Note that you need to call UserAuth.Unwrap() before calling this method if this UserAuth
// was returned from a transaction, and the transaction was committed or rolled back.
func (ua *UserAuth) Update() *UserAuthUpdateOne {
	return NewUserAuthClient(ua.config).UpdateOne(ua)
}

// Unwrap unwraps the UserAuth entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ua *UserAuth) Unwrap() *UserAuth {
	_tx, ok := ua.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAuth is not a transactional entity")
	}
	ua.config.driver = _tx.drv
	return ua
}

// String implements the fmt.Stringer.
func (ua *UserAuth) String() string {
	var builder strings.Builder
	builder.WriteString("UserAuth(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ua.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ua.UserID))
	builder.WriteString(", ")
	builder.WriteString("auth_extras=")
	builder.WriteString(ua.AuthExtras)
	builder.WriteString(", ")
	builder.WriteString("auth_provider=")
	builder.WriteString(ua.AuthProvider)
	builder.WriteString(", ")
	builder.WriteString("auth_id=")
	builder.WriteString(ua.AuthID)
	builder.WriteByte(')')
	return builder.String()
}

// UserAuths is a parsable slice of UserAuth.
type UserAuths []*UserAuth
