// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rickcts/srp/ent/predicate"
	"github.com/rickcts/srp/ent/user"
	"github.com/rickcts/srp/ent/userauth"
)

// UserAuthUpdate is the builder for updating UserAuth entities.
type UserAuthUpdate struct {
	config
	hooks    []Hook
	mutation *UserAuthMutation
}

// Where appends a list predicates to the UserAuthUpdate builder.
func (uau *UserAuthUpdate) Where(ps ...predicate.UserAuth) *UserAuthUpdate {
	uau.mutation.Where(ps...)
	return uau
}

// SetUserID sets the "user_id" field.
func (uau *UserAuthUpdate) SetUserID(i int) *UserAuthUpdate {
	uau.mutation.SetUserID(i)
	return uau
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uau *UserAuthUpdate) SetNillableUserID(i *int) *UserAuthUpdate {
	if i != nil {
		uau.SetUserID(*i)
	}
	return uau
}

// SetAuthExtras sets the "auth_extras" field.
func (uau *UserAuthUpdate) SetAuthExtras(s string) *UserAuthUpdate {
	uau.mutation.SetAuthExtras(s)
	return uau
}

// SetNillableAuthExtras sets the "auth_extras" field if the given value is not nil.
func (uau *UserAuthUpdate) SetNillableAuthExtras(s *string) *UserAuthUpdate {
	if s != nil {
		uau.SetAuthExtras(*s)
	}
	return uau
}

// SetAuthProvider sets the "auth_provider" field.
func (uau *UserAuthUpdate) SetAuthProvider(s string) *UserAuthUpdate {
	uau.mutation.SetAuthProvider(s)
	return uau
}

// SetNillableAuthProvider sets the "auth_provider" field if the given value is not nil.
func (uau *UserAuthUpdate) SetNillableAuthProvider(s *string) *UserAuthUpdate {
	if s != nil {
		uau.SetAuthProvider(*s)
	}
	return uau
}

// SetAuthID sets the "auth_id" field.
func (uau *UserAuthUpdate) SetAuthID(s string) *UserAuthUpdate {
	uau.mutation.SetAuthID(s)
	return uau
}

// SetNillableAuthID sets the "auth_id" field if the given value is not nil.
func (uau *UserAuthUpdate) SetNillableAuthID(s *string) *UserAuthUpdate {
	if s != nil {
		uau.SetAuthID(*s)
	}
	return uau
}

// SetUser sets the "user" edge to the User entity.
func (uau *UserAuthUpdate) SetUser(u *User) *UserAuthUpdate {
	return uau.SetUserID(u.ID)
}

// Mutation returns the UserAuthMutation object of the builder.
func (uau *UserAuthUpdate) Mutation() *UserAuthMutation {
	return uau.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uau *UserAuthUpdate) ClearUser() *UserAuthUpdate {
	uau.mutation.ClearUser()
	return uau
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uau *UserAuthUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uau.sqlSave, uau.mutation, uau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uau *UserAuthUpdate) SaveX(ctx context.Context) int {
	affected, err := uau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uau *UserAuthUpdate) Exec(ctx context.Context) error {
	_, err := uau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uau *UserAuthUpdate) ExecX(ctx context.Context) {
	if err := uau.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uau *UserAuthUpdate) check() error {
	if uau.mutation.UserCleared() && len(uau.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAuth.user"`)
	}
	return nil
}

func (uau *UserAuthUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(userauth.Table, userauth.Columns, sqlgraph.NewFieldSpec(userauth.FieldID, field.TypeInt))
	if ps := uau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uau.mutation.AuthExtras(); ok {
		_spec.SetField(userauth.FieldAuthExtras, field.TypeString, value)
	}
	if value, ok := uau.mutation.AuthProvider(); ok {
		_spec.SetField(userauth.FieldAuthProvider, field.TypeString, value)
	}
	if value, ok := uau.mutation.AuthID(); ok {
		_spec.SetField(userauth.FieldAuthID, field.TypeString, value)
	}
	if uau.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userauth.UserTable,
			Columns: []string{userauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uau.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userauth.UserTable,
			Columns: []string{userauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uau.mutation.done = true
	return n, nil
}

// UserAuthUpdateOne is the builder for updating a single UserAuth entity.
type UserAuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAuthMutation
}

// SetUserID sets the "user_id" field.
func (uauo *UserAuthUpdateOne) SetUserID(i int) *UserAuthUpdateOne {
	uauo.mutation.SetUserID(i)
	return uauo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uauo *UserAuthUpdateOne) SetNillableUserID(i *int) *UserAuthUpdateOne {
	if i != nil {
		uauo.SetUserID(*i)
	}
	return uauo
}

// SetAuthExtras sets the "auth_extras" field.
func (uauo *UserAuthUpdateOne) SetAuthExtras(s string) *UserAuthUpdateOne {
	uauo.mutation.SetAuthExtras(s)
	return uauo
}

// SetNillableAuthExtras sets the "auth_extras" field if the given value is not nil.
func (uauo *UserAuthUpdateOne) SetNillableAuthExtras(s *string) *UserAuthUpdateOne {
	if s != nil {
		uauo.SetAuthExtras(*s)
	}
	return uauo
}

// SetAuthProvider sets the "auth_provider" field.
func (uauo *UserAuthUpdateOne) SetAuthProvider(s string) *UserAuthUpdateOne {
	uauo.mutation.SetAuthProvider(s)
	return uauo
}

// SetNillableAuthProvider sets the "auth_provider" field if the given value is not nil.
func (uauo *UserAuthUpdateOne) SetNillableAuthProvider(s *string) *UserAuthUpdateOne {
	if s != nil {
		uauo.SetAuthProvider(*s)
	}
	return uauo
}

// SetAuthID sets the "auth_id" field.
func (uauo *UserAuthUpdateOne) SetAuthID(s string) *UserAuthUpdateOne {
	uauo.mutation.SetAuthID(s)
	return uauo
}

// SetNillableAuthID sets the "auth_id" field if the given value is not nil.
func (uauo *UserAuthUpdateOne) SetNillableAuthID(s *string) *UserAuthUpdateOne {
	if s != nil {
		uauo.SetAuthID(*s)
	}
	return uauo
}

// SetUser sets the "user" edge to the User entity.
func (uauo *UserAuthUpdateOne) SetUser(u *User) *UserAuthUpdateOne {
	return uauo.SetUserID(u.ID)
}

// Mutation returns the UserAuthMutation object of the builder.
func (uauo *UserAuthUpdateOne) Mutation() *UserAuthMutation {
	return uauo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uauo *UserAuthUpdateOne) ClearUser() *UserAuthUpdateOne {
	uauo.mutation.ClearUser()
	return uauo
}

// Where appends a list predicates to the UserAuthUpdate builder.
func (uauo *UserAuthUpdateOne) Where(ps ...predicate.UserAuth) *UserAuthUpdateOne {
	uauo.mutation.Where(ps...)
	return uauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uauo *UserAuthUpdateOne) Select(field string, fields ...string) *UserAuthUpdateOne {
	uauo.fields = append([]string{field}, fields...)
	return uauo
}

// Save executes the query and returns the updated UserAuth entity.
func (uauo *UserAuthUpdateOne) Save(ctx context.Context) (*UserAuth, error) {
	return withHooks(ctx, uauo.sqlSave, uauo.mutation, uauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uauo *UserAuthUpdateOne) SaveX(ctx context.Context) *UserAuth {
	node, err := uauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uauo *UserAuthUpdateOne) Exec(ctx context.Context) error {
	_, err := uauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uauo *UserAuthUpdateOne) ExecX(ctx context.Context) {
	if err := uauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uauo *UserAuthUpdateOne) check() error {
	if uauo.mutation.UserCleared() && len(uauo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAuth.user"`)
	}
	return nil
}

func (uauo *UserAuthUpdateOne) sqlSave(ctx context.Context) (_node *UserAuth, err error) {
	if err := uauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userauth.Table, userauth.Columns, sqlgraph.NewFieldSpec(userauth.FieldID, field.TypeInt))
	id, ok := uauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAuth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userauth.FieldID)
		for _, f := range fields {
			if !userauth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uauo.mutation.AuthExtras(); ok {
		_spec.SetField(userauth.FieldAuthExtras, field.TypeString, value)
	}
	if value, ok := uauo.mutation.AuthProvider(); ok {
		_spec.SetField(userauth.FieldAuthProvider, field.TypeString, value)
	}
	if value, ok := uauo.mutation.AuthID(); ok {
		_spec.SetField(userauth.FieldAuthID, field.TypeString, value)
	}
	if uauo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userauth.UserTable,
			Columns: []string{userauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uauo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userauth.UserTable,
			Columns: []string{userauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserAuth{config: uauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uauo.mutation.done = true
	return _node, nil
}
