// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SimpnicServerTeam/scs-aaa-server/ent/user"
	"github.com/SimpnicServerTeam/scs-aaa-server/ent/userauthevent"
)

// UserAuthEventCreate is the builder for creating a UserAuthEvent entity.
type UserAuthEventCreate struct {
	config
	mutation *UserAuthEventMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (uaec *UserAuthEventCreate) SetUserID(i int64) *UserAuthEventCreate {
	uaec.mutation.SetUserID(i)
	return uaec
}

// SetAuthProvider sets the "auth_provider" field.
func (uaec *UserAuthEventCreate) SetAuthProvider(i int64) *UserAuthEventCreate {
	uaec.mutation.SetAuthProvider(i)
	return uaec
}

// SetHost sets the "host" field.
func (uaec *UserAuthEventCreate) SetHost(s string) *UserAuthEventCreate {
	uaec.mutation.SetHost(s)
	return uaec
}

// SetUnixTs sets the "unix_ts" field.
func (uaec *UserAuthEventCreate) SetUnixTs(t time.Time) *UserAuthEventCreate {
	uaec.mutation.SetUnixTs(t)
	return uaec
}

// SetNillableUnixTs sets the "unix_ts" field if the given value is not nil.
func (uaec *UserAuthEventCreate) SetNillableUnixTs(t *time.Time) *UserAuthEventCreate {
	if t != nil {
		uaec.SetUnixTs(*t)
	}
	return uaec
}

// SetNs sets the "ns" field.
func (uaec *UserAuthEventCreate) SetNs(i int64) *UserAuthEventCreate {
	uaec.mutation.SetNs(i)
	return uaec
}

// SetNillableNs sets the "ns" field if the given value is not nil.
func (uaec *UserAuthEventCreate) SetNillableNs(i *int64) *UserAuthEventCreate {
	if i != nil {
		uaec.SetNs(*i)
	}
	return uaec
}

// SetErrorCode sets the "error_code" field.
func (uaec *UserAuthEventCreate) SetErrorCode(i int) *UserAuthEventCreate {
	uaec.mutation.SetErrorCode(i)
	return uaec
}

// SetCreatedAt sets the "created_at" field.
func (uaec *UserAuthEventCreate) SetCreatedAt(t time.Time) *UserAuthEventCreate {
	uaec.mutation.SetCreatedAt(t)
	return uaec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uaec *UserAuthEventCreate) SetNillableCreatedAt(t *time.Time) *UserAuthEventCreate {
	if t != nil {
		uaec.SetCreatedAt(*t)
	}
	return uaec
}

// SetUpdatedAt sets the "updated_at" field.
func (uaec *UserAuthEventCreate) SetUpdatedAt(t time.Time) *UserAuthEventCreate {
	uaec.mutation.SetUpdatedAt(t)
	return uaec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uaec *UserAuthEventCreate) SetNillableUpdatedAt(t *time.Time) *UserAuthEventCreate {
	if t != nil {
		uaec.SetUpdatedAt(*t)
	}
	return uaec
}

// SetUser sets the "user" edge to the User entity.
func (uaec *UserAuthEventCreate) SetUser(u *User) *UserAuthEventCreate {
	return uaec.SetUserID(u.ID)
}

// Mutation returns the UserAuthEventMutation object of the builder.
func (uaec *UserAuthEventCreate) Mutation() *UserAuthEventMutation {
	return uaec.mutation
}

// Save creates the UserAuthEvent in the database.
func (uaec *UserAuthEventCreate) Save(ctx context.Context) (*UserAuthEvent, error) {
	uaec.defaults()
	return withHooks(ctx, uaec.sqlSave, uaec.mutation, uaec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uaec *UserAuthEventCreate) SaveX(ctx context.Context) *UserAuthEvent {
	v, err := uaec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uaec *UserAuthEventCreate) Exec(ctx context.Context) error {
	_, err := uaec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uaec *UserAuthEventCreate) ExecX(ctx context.Context) {
	if err := uaec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uaec *UserAuthEventCreate) defaults() {
	if _, ok := uaec.mutation.UnixTs(); !ok {
		v := userauthevent.DefaultUnixTs()
		uaec.mutation.SetUnixTs(v)
	}
	if _, ok := uaec.mutation.Ns(); !ok {
		v := userauthevent.DefaultNs()
		uaec.mutation.SetNs(v)
	}
	if _, ok := uaec.mutation.CreatedAt(); !ok {
		v := userauthevent.DefaultCreatedAt()
		uaec.mutation.SetCreatedAt(v)
	}
	if _, ok := uaec.mutation.UpdatedAt(); !ok {
		v := userauthevent.DefaultUpdatedAt()
		uaec.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uaec *UserAuthEventCreate) check() error {
	if _, ok := uaec.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserAuthEvent.user_id"`)}
	}
	if _, ok := uaec.mutation.AuthProvider(); !ok {
		return &ValidationError{Name: "auth_provider", err: errors.New(`ent: missing required field "UserAuthEvent.auth_provider"`)}
	}
	if _, ok := uaec.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "UserAuthEvent.host"`)}
	}
	if _, ok := uaec.mutation.UnixTs(); !ok {
		return &ValidationError{Name: "unix_ts", err: errors.New(`ent: missing required field "UserAuthEvent.unix_ts"`)}
	}
	if _, ok := uaec.mutation.Ns(); !ok {
		return &ValidationError{Name: "ns", err: errors.New(`ent: missing required field "UserAuthEvent.ns"`)}
	}
	if _, ok := uaec.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "UserAuthEvent.error_code"`)}
	}
	if _, ok := uaec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAuthEvent.created_at"`)}
	}
	if _, ok := uaec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAuthEvent.updated_at"`)}
	}
	if len(uaec.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserAuthEvent.user"`)}
	}
	return nil
}

func (uaec *UserAuthEventCreate) sqlSave(ctx context.Context) (*UserAuthEvent, error) {
	if err := uaec.check(); err != nil {
		return nil, err
	}
	_node, _spec := uaec.createSpec()
	if err := sqlgraph.CreateNode(ctx, uaec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uaec.mutation.id = &_node.ID
	uaec.mutation.done = true
	return _node, nil
}

func (uaec *UserAuthEventCreate) createSpec() (*UserAuthEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAuthEvent{config: uaec.config}
		_spec = sqlgraph.NewCreateSpec(userauthevent.Table, sqlgraph.NewFieldSpec(userauthevent.FieldID, field.TypeInt))
	)
	if value, ok := uaec.mutation.AuthProvider(); ok {
		_spec.SetField(userauthevent.FieldAuthProvider, field.TypeInt64, value)
		_node.AuthProvider = value
	}
	if value, ok := uaec.mutation.Host(); ok {
		_spec.SetField(userauthevent.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := uaec.mutation.UnixTs(); ok {
		_spec.SetField(userauthevent.FieldUnixTs, field.TypeTime, value)
		_node.UnixTs = value
	}
	if value, ok := uaec.mutation.Ns(); ok {
		_spec.SetField(userauthevent.FieldNs, field.TypeInt64, value)
		_node.Ns = value
	}
	if value, ok := uaec.mutation.ErrorCode(); ok {
		_spec.SetField(userauthevent.FieldErrorCode, field.TypeInt, value)
		_node.ErrorCode = value
	}
	if value, ok := uaec.mutation.CreatedAt(); ok {
		_spec.SetField(userauthevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uaec.mutation.UpdatedAt(); ok {
		_spec.SetField(userauthevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := uaec.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userauthevent.UserTable,
			Columns: []string{userauthevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserAuthEventCreateBulk is the builder for creating many UserAuthEvent entities in bulk.
type UserAuthEventCreateBulk struct {
	config
	err      error
	builders []*UserAuthEventCreate
}

// Save creates the UserAuthEvent entities in the database.
func (uaecb *UserAuthEventCreateBulk) Save(ctx context.Context) ([]*UserAuthEvent, error) {
	if uaecb.err != nil {
		return nil, uaecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uaecb.builders))
	nodes := make([]*UserAuthEvent, len(uaecb.builders))
	mutators := make([]Mutator, len(uaecb.builders))
	for i := range uaecb.builders {
		func(i int, root context.Context) {
			builder := uaecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAuthEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uaecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uaecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uaecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uaecb *UserAuthEventCreateBulk) SaveX(ctx context.Context) []*UserAuthEvent {
	v, err := uaecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uaecb *UserAuthEventCreateBulk) Exec(ctx context.Context) error {
	_, err := uaecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uaecb *UserAuthEventCreateBulk) ExecX(ctx context.Context) {
	if err := uaecb.Exec(ctx); err != nil {
		panic(err)
	}
}
