// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SimpnicServerTeam/scs-aaa-server/ent/user"
	"github.com/SimpnicServerTeam/scs-aaa-server/ent/usermfa"
)

// UserMFA is the model entity for the UserMFA schema.
type UserMFA struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SMS, EMAIL, NUM_MATCH, etc.
	MfaMethod string `json:"mfa_method,omitempty"`
	// Params holds the value of the "params" field.
	Params string `json:"params,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserMFAQuery when eager-loading is set.
	Edges        UserMFAEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserMFAEdges holds the relations/edges for other nodes in the graph.
type UserMFAEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserMFAEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserMFA) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usermfa.FieldID, usermfa.FieldUserID:
			values[i] = new(sql.NullInt64)
		case usermfa.FieldMfaMethod, usermfa.FieldParams:
			values[i] = new(sql.NullString)
		case usermfa.FieldCreatedAt, usermfa.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserMFA fields.
func (um *UserMFA) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usermfa.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			um.ID = int(value.Int64)
		case usermfa.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				um.UserID = value.Int64
			}
		case usermfa.FieldMfaMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mfa_method", values[i])
			} else if value.Valid {
				um.MfaMethod = value.String
			}
		case usermfa.FieldParams:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field params", values[i])
			} else if value.Valid {
				um.Params = value.String
			}
		case usermfa.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				um.CreatedAt = value.Time
			}
		case usermfa.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				um.UpdatedAt = value.Time
			}
		default:
			um.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserMFA.
// This includes values selected through modifiers, order, etc.
func (um *UserMFA) Value(name string) (ent.Value, error) {
	return um.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserMFA entity.
func (um *UserMFA) QueryUser() *UserQuery {
	return NewUserMFAClient(um.config).QueryUser(um)
}

// Update returns a builder for updating this UserMFA.
// Note that you need to call UserMFA.Unwrap() before calling this method if this UserMFA
// was returned from a transaction, and the transaction was committed or rolled back.
func (um *UserMFA) Update() *UserMFAUpdateOne {
	return NewUserMFAClient(um.config).UpdateOne(um)
}

// Unwrap unwraps the UserMFA entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (um *UserMFA) Unwrap() *UserMFA {
	_tx, ok := um.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserMFA is not a transactional entity")
	}
	um.config.driver = _tx.drv
	return um
}

// String implements the fmt.Stringer.
func (um *UserMFA) String() string {
	var builder strings.Builder
	builder.WriteString("UserMFA(")
	builder.WriteString(fmt.Sprintf("id=%v, ", um.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", um.UserID))
	builder.WriteString(", ")
	builder.WriteString("mfa_method=")
	builder.WriteString(um.MfaMethod)
	builder.WriteString(", ")
	builder.WriteString("params=")
	builder.WriteString(um.Params)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(um.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(um.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserMFAs is a parsable slice of UserMFA.
type UserMFAs []*UserMFA
