// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rickcts/srp/ent/predicate"
	"github.com/rickcts/srp/ent/userauthevent"
)

// UserAuthEventDelete is the builder for deleting a UserAuthEvent entity.
type UserAuthEventDelete struct {
	config
	hooks    []Hook
	mutation *UserAuthEventMutation
}

// Where appends a list predicates to the UserAuthEventDelete builder.
func (uaed *UserAuthEventDelete) Where(ps ...predicate.UserAuthEvent) *UserAuthEventDelete {
	uaed.mutation.Where(ps...)
	return uaed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uaed *UserAuthEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uaed.sqlExec, uaed.mutation, uaed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uaed *UserAuthEventDelete) ExecX(ctx context.Context) int {
	n, err := uaed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uaed *UserAuthEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userauthevent.Table, sqlgraph.NewFieldSpec(userauthevent.FieldID, field.TypeInt))
	if ps := uaed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uaed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uaed.mutation.done = true
	return affected, err
}

// UserAuthEventDeleteOne is the builder for deleting a single UserAuthEvent entity.
type UserAuthEventDeleteOne struct {
	uaed *UserAuthEventDelete
}

// Where appends a list predicates to the UserAuthEventDelete builder.
func (uaedo *UserAuthEventDeleteOne) Where(ps ...predicate.UserAuthEvent) *UserAuthEventDeleteOne {
	uaedo.uaed.mutation.Where(ps...)
	return uaedo
}

// Exec executes the deletion query.
func (uaedo *UserAuthEventDeleteOne) Exec(ctx context.Context) error {
	n, err := uaedo.uaed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userauthevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uaedo *UserAuthEventDeleteOne) ExecX(ctx context.Context) {
	if err := uaedo.Exec(ctx); err != nil {
		panic(err)
	}
}
